---
    - name: copying file
      win_copy:
        src: "{{ path_to_file }}{{ item }}"
        dest: "{{ destination_path }}{{ item }}"
        owner: centos
        group: centos
        mode: 0644
      with_items: "{{ filenames_to_copy.split(',') }}"

    - name: Print a message
      debug:
        msg: "########## Copied Successfully ##########"

    - name: Executing SQL Files
      win_command: sqlcmd -i "{{ destination_path }}{{ item }}"
      register: sqlcmd_out
      when: item | length > 0 
      with_items: "{{ filenames_to_execute.split(',') }}"
    
    - name : Print a message
      debug:
        msg: "######## The output is {{ sqlcmd_out }}"

    - name: Print a message
      debug:
        msg: "########## Exxecuted Successfully ##########"

    - name: Use of Jinja Template
      template:
        src: version.config.j2
        dest: "{{ destination_path }}version.config.txt"
