---
#- hosts: all
#  vars:
filenames_to_copy: "CommandLog-01.sql,CommandExecute-02.sql,DatabaseIntegrityCheck-03.sql,IndexOptimize-04.sql"
#filenames_to_copy: ""

filenames_to_execute: "CommandLog-01.sql,CommandExecute-02.sql,DatabaseIntegrityCheck-03.sql,IndexOptimize-04.sql"
#filenames_to_execute: ""
destination_path: C:\Users\Administrator\Desktop\task\


#Databases

data_base: master

